### PR TITLE
fix: time formatting bun2719

### PR DESCRIPTION
**Pull request by BrianJiang2021**
Jira: [BUN-2719](https://bigc-b2b.atlassian.net/browse/BUN-2719)

## What/Why?
time formatting

## Rollout/Rollback
undo pr

## Testing

image

### CODE REVIEW

**Review by LeoChowChina — APPROVED** [review]

**Review by kity-bundle — APPROVED** [review]

**Comment by SE-Graham** [comment]
@BrianJiang2021 

I can't seem to get B2B to run when it includes this PR.

It results in following error in the browser console

mui-B9wxrMZb.js:17 Uncaught (in promise) 
TypeError: Cannot set properties of undefined (setting 'exports')
    at mui-B9wxrMZb.js:17:4146
    at Nc (mui-B9wxrMZb.js:17:4201)
    at eReact-CjZuucTw.js:1:3858

**Comment by BrianJiang2021** [comment]
> exports

Because I haven't reproduced the problem you mentioned.
So can you provide a screenshot? Or a video of the whole process?
This will help me understand what happened when the problem occurred.

If you are running locally, you may try to reinstall the dependency package to see if it can solve the problem.

**Comment by BrianJiang2021** [comment]
Hi @SE-Graham 

Because I haven't reproduced the problem you mentioned.
So can you provide a screenshot? Or a video of the whole process?
This will help me understand what happened when the problem occurred.

If you are running locally, you may try to reinstall the dependency package to see if it can solve the problem.

**Comment by SE-Graham** [comment]
Hi @BrianJiang2021 

I've started fresh using the main branch. 

Video of build process and screenshot of error in chrome.

https://swimming.box.com/shared/static/l6on6t8giip6jkr0wvpin8soi00fuv31.mov

Screenshot 2024-09-06 at 09 53 19

Screenshot 2024-09-06 at 10 16 22

**Comment by BrianJiang2021** [comment]
Hi @SE-Graham 
After the build is completed, what operations are performed? Can you record the entire process from running the project to the page error?
If so, can you provide the .env configuration?

If you are running at http://localhost:3xxx/, there may be cross-domain issues or other issues
The way we run locally has changed now. For details, you can refer to
https://github.com/bigcommerce/b2b-buyer-portal?tab=readme-ov-file#-local-development
and https://github.com/bigcommerce/b2b-buyer-portal?tab=readme-ov-file#running-project-locally

Below is the video I recorded.
I reinstalled the dependency package in the main branch and successfully built it. Then I configured our test store according to the tutorial in git README.
As you can see, the project is running normally and there is no problem you reported.

https://github.com/user-attachments/assets/bd19ba29-9fb7-440b-a6ff-a25d304ab849

**Comment by SE-Graham** [comment]
Hi @BrianJiang2021 

This is being deployed to our BC Sandbox store, this use to work without issues.

The files are copied over to our Cloudflare R2 bucket and the footer script is updated with the new URLs.

The error you see appears when loading the home page or any other page, instead of getting the b2b login page you get the BC login page.

```
<script>
  window.b3CheckoutConfig = {
    routes: {
      dashboard: '/account.php?action=order_status',
    },
  }
  window.B3 = {
    setting: {
      store_hash: "{{settings.store_hash}}",
      channel_id: 1,
      platform: 'bigcommerce',
      b2b_url: 'https://api-b2b.bigcommerce.com',
      captcha_setkey: '6LdGN_sgAAAAAGYFg1lmVoakQ8QXxbhWqZ1GpYaJ',
    },
    'dom.checkoutRegisterParentElement': '#checkout-app',
    'dom.registerElement':
      '[href^="/login.php"], #checkout-customer-login, [href="/login.php"] .navUser-item-loginLabel, #checkout-customer-returning .form-legend-container [href="#"]',
    'dom.openB3Checkout': 'checkout-customer-continue',
    before_login_goto_page: '/account.php?action=order_status',
    checkout_super_clear_session: 'true',
    'dom.navUserLoginElement': '.navUser-item.navUser-item--account',
  }
</script>
<script type="module" crossorigin src="https://b2b-buyer-portal.swimming.org/staging/v1.0.41/index.1HrXa0Ye.js"></script>
<script nomodule crossorigin src="https://b2b-buyer-portal.swimming.org/staging/v1.0.41/polyfills-legacy.CXJzAxq-.js"></script>
<script nomodule crossorigin src="https://b2b-buyer-portal.swimming.org/staging/v1.0.41/index-legacy.DyTIk_DM.js"></script>
```

```
# URL of the B2B API, if doing local development, this should be the URL of the local B2B API with its own port
VITE_B2B_URL=https://api-b2b.bigcommerce.com

# URL of the B2B Socket - this should be the same as the B2B API URL
VITE_B2B_SOCKET_URL=https://api-b2b.bigcommerce.com

# URL of the B2B Translation Service - if doing local development, try with localhost:5000 or check the service URL
VITE_TRANSLATION_SERVICE_URL=https://api-b2b.bigcommerce.com

# Captcha Site Key for the storefront
VITE_CATPCHA_SETKEY="6LdGN_sgAAAAAGYFg1lmVoakQ8QXxbhWqZ1GpYaJ"

# Client ID issued by B2B Edition for the storefront
VITE_B2B_CLIENT_ID="dl7c39mdpul6hyc489yk0vzxl6jesyx"

# Set this to TRUE to debug in your default storefront
VITE_LOCAL_DEBUG=FALSE

# URL where the GraphQL is hosted, usually the same one as B2B_URL_API. If the GraphQL API is hosted locally, set this to the local URL
VITE_LOCAL_GRAPHQL_ORIGIN="https://api-b2b.bigcommerce.com"

# For custom host, set this to the absolute path where will be hosted the generated assets after your run `yarn build`
VITE_ASSETS_ABSOLUTE_PATH="https://b2b-buyer-portal.swimming.org/staging/v1.0.41/assets/"
```


**Previous Build** 

If I revert the footer to a previous build everything works fine.

```
<script>
  window.b3CheckoutConfig = {
    routes: {
      dashboard: '/account.php?action=order_status',
    },
  }
  window.B3 = {
    setting: {
      store_hash: "{{settings.store_hash}}",
      channel_id: 1,
      platform: 'bigcommerce',
      b2b_url: 'https://api-b2b.bigcommerce.com',
      captcha_setkey: '6LdGN_sgAAAAAGYFg1lmVoakQ8QXxbhWqZ1GpYaJ',
    },
    'dom.checkoutRegisterParentElement': '#checkout-app',
    'dom.registerElement':
      '[href^="/login.php"], #checkout-customer-login, [href="/login.php"] .navUser-item-loginLabel, #checkout-customer-returning .form-legend-container [href="#"]',
    'dom.openB3Checkout': 'checkout-customer-continue',
    before_login_goto_page: '/account.php?action=order_status',
    checkout_super_clear_session: 'true',
    'dom.navUserLoginElement': '.navUser-item.navUser-item--account',
  }
</script>
<script type="module" crossorigin src="https://b2b-buyer-portal.swimming.org/staging/v1.0.27/index.DBdZAyf5.js"></script>
<script nomodule crossorigin src="https://b2b-buyer-portal.swimming.org/staging/v1.0.27/polyfills-legacy.CXJzAxq-.js"></script>
<script nomodule crossorigin src="https://b2b-buyer-portal.swimming.org/staging/v1.0.27/index-legacy.D_tw_MmD.js"></script>
```

**Comment by BrianJiang2021** [comment]
Hi, @SE-Graham 

you can try to modify the node to version 20.17.0 and redeploy it

**Comment by SE-Graham** [comment]
Hi, @BrianJiang2021 

I've tried 20.17.0 and still getting the same error when deployed.

If you deploy it and don't run it locally does it work for you?

```
mui-B9wxrMZb.js:17 Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'exports')
    at mui-B9wxrMZb.js:17:4146
    at Nc (mui-B9wxrMZb.js:17:4201)
    at eReact-CjZuucTw.js:1:3858
(anonymous) @ mui-B9wxrMZb.js:17
Nc @ mui-B9wxrMZb.js:17
(anonymous) @ eReact-CjZuucTw.js:1
requestIdleCallback
(anonymous) @ index.CMJRwx-K.js:2
```

**Comment by BrianJiang2021** [comment]
Hi, @SE-Graham 

I built it through local yarn, started dist with http-server, and reproduced this problem.

Please try modifying the following:
packages==> tsconfig ==> vite.json ==> Modify esModuleInterop to true

image

image

image

Hope it helps you

**Comment by SE-Graham** [comment]
Hi @BrianJiang2021 ,

I've given that a try and stills seeing the same issue.

Updated packages==> tsconfig ==> vite.json ==> Modify esModuleInterop to true
update .env file path
yarn clean
yarn
yarn build
upload files
update footer

**Comment by grahamspr86** [comment]
Hi @BrianJiang2021 ,

Not sure where else to go with this, any other suggestions?

Thanks 
Graham

**Comment by BrianJiang2021** [comment]
Hi @grahamspr86 

I packaged it locally, started a service locally, and applied the relevant links in the test store.

When esModuleInterop is set to false, the result is as follows: 
In this case, I reproduced the problem.

cdafb7fda2be75cb824cd4d7dfe31c4b
76bb321e782fcfda02a59b7b6ad914e8
cb3c755e2ce61e2bd047c099afdebb6b


When esModuleInterop is set to true, the result is as follows:
d92e7893f4f9aad1aa3fa9bb4a2cb835
3dd93dac0e332f2d99b1930a49597ac5

In this case, it works normally (Note: If you modify the [vite.json] file alone, the cached [vite.json data] will be used during the build. So in order to ensure that the updated [vite.json] file is used, please modify some other files, such as src->App.tsx)

**Pull request merged**
